version: '2'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: haxetest
    ports:
      - 127.0.0.1:5432:5432
